from PyQt5.QtWidgets import *
from PyQt5.QtCore import *


class LoginDialog(QDialog):
    def __init__(self, parent):
        super().__init__(parent)
        self.parent_widget = parent
        self.setupUi()

    def setupUi(self):
        self.verticalLayout = QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QTabWidget(self)
        self.tabWidget.setObjectName("tabWidget")
        self.first_tab = QWidget()
        self.first_tab.setObjectName("first_tab")
        self.horizontalLayout = QHBoxLayout(self.first_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout = QGridLayout(self)
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setVerticalSpacing(17)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.username1 = QLineEdit(self.first_tab)
        self.username1.setMinimumSize(QSize(0, 30))
        self.username1.setObjectName("username1")
        self.gridLayout.addWidget(self.username1, 1, 1, 1, 1)
        self.password1 = QLineEdit(self.first_tab)
        self.password1.setMinimumSize(QSize(0, 30))
        self.password1.setObjectName("password1")
        self.gridLayout.addWidget(self.password1, 2, 1, 1, 1)
        self.label_2 = QLabel(self.first_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_1 = QLabel(self.first_tab)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 1, 0, 1, 1)
        spacerItem2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.tabWidget.addTab(self.first_tab, "")
        self.second_tab = QWidget()
        self.second_tab.setObjectName("second_tab")
        self.horizontalLayout_2 = QHBoxLayout(self.second_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setVerticalSpacing(17)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem5 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 3, 1, 1, 1)
        self.username2 = QLineEdit(self.second_tab)
        self.username2.setMinimumSize(QSize(0, 30))
        self.username2.setObjectName("username2")
        self.gridLayout_2.addWidget(self.username2, 1, 1, 1, 1)
        self.password2 = QLineEdit(self.second_tab)
        self.password2.setMinimumSize(QSize(0, 30))
        self.password2.setObjectName("password2")
        self.gridLayout_2.addWidget(self.password2, 2, 1, 1, 1)
        self.label_3 = QLabel(self.second_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QLabel(self.second_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem6 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        spacerItem7 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.tabWidget.addTab(self.second_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.pushButton = QPushButton()
        self.pushButton.setMinimumSize(QSize(0, 40))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi()
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(self.parent_widget.login_dialog_save)

    def retranslateUi(self):
        _translate = QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "账号信息"))
        self.label_2.setText(_translate("Dialog", "密码:"))
        self.label_1.setText(_translate("Dialog", "账号: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.first_tab), _translate("Dialog", "第一页面"))
        self.label_3.setText(_translate("Dialog", "密码:"))
        self.label_4.setText(_translate("Dialog", "账号: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.second_tab), _translate("Dialog", "第二页面"))
        self.pushButton.setText(_translate("Dialog", "保存"))


