# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(469, 339)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 65))
        self.widget.setStyleSheet("border-bottom:1px solid #d1e9fa;")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(45, 45))
        self.label_2.setStyleSheet("border-image: url(:/user/user_icon.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color: rgb(23, 143, 230);\n"
"font-size: 23px;\n"
"font-weight: bold;\n"
"line-height: 60px;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(-1, 11, -1, 11)
        self.gridLayout_2.setSpacing(11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.username = QtWidgets.QLineEdit(self.widget_3)
        self.username.setMinimumSize(QtCore.QSize(0, 40))
        self.username.setStyleSheet("border: none;\n"
"border-bottom:1px solid lightgray;\n"
"background-color: transparent;\n"
"font-size:16px;")
        self.username.setClearButtonEnabled(True)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 0, 0, 1, 2)
        self.password = QtWidgets.QLineEdit(self.widget_3)
        self.password.setMinimumSize(QtCore.QSize(0, 40))
        self.password.setStyleSheet("border: none;\n"
"border-bottom:1px solid lightgray;\n"
"background-color: transparent;\n"
"font-size:16px;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(False)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 0, 1, 2)
        self.auto_login = QtWidgets.QCheckBox(self.widget_3)
        self.auto_login.setObjectName("auto_login")
        self.gridLayout.addWidget(self.auto_login, 2, 0, 1, 1)
        self.remenber = QtWidgets.QCheckBox(self.widget_3)
        self.remenber.setObjectName("remenber")
        self.gridLayout.addWidget(self.remenber, 2, 1, 1, 1, QtCore.Qt.AlignRight)
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 2)
        self.gridLayout_2.addWidget(self.widget_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.login)
        self.remenber.toggled['bool'].connect(Form.visible)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "用户登录"))
        self.auto_login.setText(_translate("Form", "自动登录"))
        self.remenber.setText(_translate("Form", "记住密码"))
        self.pushButton.setText(_translate("Form", "登录"))
import images_rc
