# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(444, 320)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.first_tab = QtWidgets.QWidget()
        self.first_tab.setObjectName("first_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.first_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setVerticalSpacing(17)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.username1 = QtWidgets.QLineEdit(self.first_tab)
        self.username1.setMinimumSize(QtCore.QSize(0, 30))
        self.username1.setObjectName("username1")
        self.gridLayout.addWidget(self.username1, 1, 1, 1, 1)
        self.password1 = QtWidgets.QLineEdit(self.first_tab)
        self.password1.setMinimumSize(QtCore.QSize(0, 30))
        self.password1.setObjectName("password1")
        self.gridLayout.addWidget(self.password1, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.first_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.first_tab)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.tabWidget.addTab(self.first_tab, "")
        self.second_tab = QtWidgets.QWidget()
        self.second_tab.setObjectName("second_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.second_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setVerticalSpacing(17)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 3, 1, 1, 1)
        self.username2 = QtWidgets.QLineEdit(self.second_tab)
        self.username2.setMinimumSize(QtCore.QSize(0, 30))
        self.username2.setObjectName("username2")
        self.gridLayout_2.addWidget(self.username2, 1, 1, 1, 1)
        self.password2 = QtWidgets.QLineEdit(self.second_tab)
        self.password2.setMinimumSize(QtCore.QSize(0, 30))
        self.password2.setObjectName("password2")
        self.gridLayout_2.addWidget(self.password2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.second_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.second_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.tabWidget.addTab(self.second_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.pushButton.clicked.connect(Dialog.save_account)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "账号信息"))
        self.label_2.setText(_translate("Dialog", "密码:"))
        self.label_1.setText(_translate("Dialog", "账号: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.first_tab), _translate("Dialog", "第一页面"))
        self.label_3.setText(_translate("Dialog", "密码:"))
        self.label_4.setText(_translate("Dialog", "账号: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.second_tab), _translate("Dialog", "第二页面"))
        self.pushButton.setText(_translate("Dialog", "保存"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
